### ISSUE TITLE
No codes found!

### ISSUE THREAD

**Issue by Freeze777** [joaopalotti/mycikmcup2016#1]
Hi joaopallotti,

Could you please add your scripts for reference.

Thanks in advance :)

**Comment by joaopalotti** [comment]
Hi, thanks for your interest. I will upload my code by the end of this week.
Cheers

**Comment by Freeze777** [comment]
Great :+1:

**Comment by joaopalotti** [comment]
Added the main script to generate the featureset used in my approach.

**Comment by Freeze777** [comment]
Thanks a lot
